name: GMA
description: Multi-package settings
stages:
  - fake
  - prod
countries:
  - in
  - vn
  - ph
  - id
apps:
  - name: self_care
    folder: capp
    description: Customer application [CAPP]
    flavor: fakein
    stages:
      - fake
      - prod
    countries:
      - in
      - vn
      - ph
      - id
    exclude_packages:
      - mapp_**
    
  - name: mapp
    folder: mapp
    description: Merchant application  [MAPP]
    flavor: fakein
    stages:
      - fake
      - prod
    countries:
      - in
      - vn
      - ph
      - id
    exclude_packages:
      - capp_**
  - name: widget_catalog
    folder: widget_catalog
    description: Widget catalog
  - name: dynamic_forms_playground
    folder: dynamic_forms_playground
    description: Dynamic forms playground  
packages:
  - packages/**
  - plugins/**

runners:
