name: gmat
description: Multi-package repo tools.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansi_styles: ^0.3.0
  args: ^2.2.0
  collection: ^1.15.0-nullsafety.4
  dart_console: ^1.0.0
  pool: ^1.5.0
  cli_util: ^0.3.3
  pubspec: ^2.0.1
  yaml: ^3.1.0
  glob: ^2.0.1
dev_dependencies:
  pedantic: ^1.10.0
  nock: ^1.2.0
  test: ^1.17.5
  lints: ^1.0.1
executables:
  gmat:
